### PR TITLE
2020-tokyo: Update sponsors

### PR DESCRIPTION
**Pull request by superbrothers**
This PR updates gold and silver sponsors of KCD Tokyo 2020.

### CODE REVIEW

**Comment by MasayaAoyama** [comment]
LGTM

**Comment by KTan1226** [comment]
Hi @superbrothers- is this still a work in progress?

**Comment by superbrothers** [comment]
Yes, it is. One company's logo is a bit small, so we're asking if we can resize the image.

image

**Comment by superbrothers** [comment]
@KTan1226 I removed the WIP flag. Could you review this PR?

**Pull request merged**
