### PR TITLE
Add sponsors template

### LINKED ISSUE #30: Compile Sponsor pages
Please convert the sponsor pages to be YAML that is compiled to show the images rather than markdown. I would suggest the following YAML to produce https://kubernetescommunitydays.org/events/2020-bouvet-island/sponsors/

Categories should be displayed in the order shown, but items within a category should be displayed alphabetically.

```yml
sponsors:
  - category:
    name: Diamond
    items:
      - item:
        name: Oceanic Airways
        url: 'https://en.wikipedia.org/wiki/Oceanic_Airlines'
        logo: sponsor-oceanic-airways.svg
  - category:
    name: Platinum
    items:
      - item:
        name: BnL
        url: 'https://en.wikipedia.org/wiki/List_of_Pixar_film_references#Buy_n_Large_(BnL)'
        logo: sponsor-bnl.svg
```

### PR DESCRIPTION
**Pull request by lucperkins**
Resolves #30

For an example page, see [here](https://deploy-preview-40--kubernetes-community-days.netlify.com/events/2020-bouvet-island/sponsors/). The aesthetic isn't yet super polished but this provides the desired UI.

### CODE REVIEW

**Comment by dankohn** [comment]
Not quite working yet. Please note that sponsor logos also need to be links. For example, Oceanic should link to https://en.wikipedia.org/wiki/Oceanic_Airlines.

**Comment by lucperkins** [comment]
@dankohn Could you check again? It's looking fine on my end.

**Comment by dankohn** [comment]
It looks great. However, it was blocked by [Ublock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en). Would you mind spending 10 minutes to see if not calling things `class=sponsor-logo-container` produces different results?

**Comment by lucperkins** [comment]
@dankohn Okay, that seems to have done the trick

**Comment by dankohn** [comment]
It did, thank you. I think this looks fantastic.

**Pull request merged**
