### PR TITLE
Prettify London sponsor page, add community partners, update volunteers

### PR DESCRIPTION
**Pull request by oicheryl**

### CODE REVIEW

**Comment by oicheryl** [comment]
@Arau @gianarb @jmickey

**Comment by dankohn** [comment]
Please add an LGTM @oicheryl

**Comment by dankohn** [comment]
Don’t you want to list your initial sponsors like this?

https://deploy-preview-301--kubernetes-community-days.netlify.com/events/2020-amsterdam/

**Comment by oicheryl** [comment]
I would like to get this out first.

**Pull request merged**
