### PR TITLE
Adding a "Tickets" section to the menubar

### PR DESCRIPTION
**Pull request by ams0**
I took the liberty to modify some of the common theme files to add a "Tickets" section to the navbar. I think it's a good button to have for people to immediately find the information about ticket sale.

### CODE REVIEW

**Comment by ams0** [comment]
LGTM!

**Comment by ams0** [comment]
bump!

**Comment by dankohn** [comment]
Would you mind `register` instead of `tickets`? I believe that's best practice from things like https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/ and https://devopsdays.org/events/2020-madrid/welcome/.

I certainly agree the top-level menu is needed.

**Comment by ams0** [comment]
good one, addressed in 7a70ba5078465297d1ec8ae19ccd7743ecfbe31c

**Pull request merged**
