### PR TITLE
Add KCD Bengaluru, India 2020

### PR DESCRIPTION
**Pull request by kmova**
Ref #169 

This PR adds the initial information about KCD Bengaluru 2020

### CODE REVIEW

**Comment by nikhita** [comment]
Left some comments on https://github.com/kmova/kubernetes-community-days/pull/1

**Comment by nikhita** [comment]
Overall lgtm :+1:

**Comment by kmova** [comment]
@dankohn @KTan1226 can you please take a look and see if this can be merged.

**Comment by dankohn** [comment]
Can you please add a background image for https://deploy-preview-306--kubernetes-community-days.netlify.com/events/2020-bengaluru/.

**Comment by kmova** [comment]
Thanks @dankohn for the review. I have updated the background image.

**Comment by dankohn** [comment]
Could you please replace the sponsor logos with SVGs from https://landscape.cncf.io/format=card-mode&grouping=no. Note that the sponsor logos also need to include the company name.

**Comment by kmova** [comment]
Thanks @dankohn for the tip on the SVG images. Updated this PR with logos from the CNCF  landscape.

**Pull request merged**
