### PR TITLE
fix: update broken links

### PR DESCRIPTION
**Pull request by raelga**
- This PRs updates all the relative broken links to md files within the directory.
- Removes the Bouvet Island website example text, as files are missing
- Adds some missing `md` extensions

TODO: All help.bevylabs.com are failing with `response 404 (backend NotFound), service rules for the path non-existent `

### CODE REVIEW

**Comment by AudMonte01** [comment]
Hi @raelga - the PR links have been fixed as of two weeks ago. Please let me know if you are still seeing 404 messages.

Where is the Bouvet example text you are referring to?

In regards to Bevy labs, here are some Bevy Academy videos that might help: http://vimeo.com/showcase/bevy-virtual-conference

**Review by AudMonte01 — APPROVED** [review]

**Comment by raelga** [comment]
Hello @AudMonte01 there are still several broken links that were fixed in this PR, for instance:

https://github.com/cncf/kubernetes-community-days/blob/main/planning/about-organizing.md

In the section:

https://github.com/cncf/kubernetes-community-days/blob/main/planning/about-organizing.md#assembling-your-team

**Comment by AudMonte01** [comment]
Thank you @raelga - I just fixed the 404's in that section as well as the section below it. We appreciate your eyes catching those broken links.

**Comment by raelga** [comment]
Hello @AudMonte01 ,

There are still broken links at https://github.com/cncf/kubernetes-community-days/blob/main/planning/master-timeline.md.

**Comment by AudMonte01** [comment]
> Hello @AudMonte01 ,
> 
> There are still broken links at https://github.com/cncf/kubernetes-community-days/blob/main/planning/master-timeline.md.

Thank you for finding more broken links! I have fixed all of them on the master timeline page. Please let me know if you see others - we appreciate your time and eyes. :-)

**Pull request closed without merging**
